### ISSUE TITLE
Improve output of commands

### ISSUE THREAD

**Issue by sabinebaer** [alexander-schranz/sulu-backend-bundle#30]
It should be more obvious that something has to be done, e.g. add a sentence after the generation of the controller "Add the following to the admin routing of your bundle:".

Maybe you could even include instructions to generate an admin routing file if not already existent:

```
client_website_admin:
    type: rest
    resource: "@ClientWebsiteBundle/Resources/config/routing_admin.yml"
    prefix: /admin/api
```
